// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file accountable/system/v1/system.proto (package accountable.system.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file accountable/system/v1/system.proto.
 */
export const file_accountable_system_v1_system: GenFile = /*@__PURE__*/
  fileDesc("CiJhY2NvdW50YWJsZS9zeXN0ZW0vdjEvc3lzdGVtLnByb3RvEhVhY2NvdW50YWJsZS5zeXN0ZW0udjEiEwoRR2V0UnVudGltZVJlcXVlc3QibQoSR2V0UnVudGltZVJlc3BvbnNlEhIKCnJlbGVhc2VfaWQYASABKAkSLwoLc2VydmVyX3RpbWUYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhIKCnJlcXVlc3RfaWQYAyABKAkycgoNU3lzdGVtU2VydmljZRJhCgpHZXRSdW50aW1lEiguYWNjb3VudGFibGUuc3lzdGVtLnYxLkdldFJ1bnRpbWVSZXF1ZXN0GikuYWNjb3VudGFibGUuc3lzdGVtLnYxLkdldFJ1bnRpbWVSZXNwb25zZULjAQoZY29tLmFjY291bnRhYmxlLnN5c3RlbS52MUILU3lzdGVtUHJvdG9QAVpDZ2l0aHViLmNvbS9hY2N0YmwvYWNjb3VudGFibGUvZ2VuL2dvL2FjY291bnRhYmxlL3N5c3RlbS92MTtzeXN0ZW12MaICA0FTWKoCFUFjY291bnRhYmxlLlN5c3RlbS5WMcoCFUFjY291bnRhYmxlXFN5c3RlbVxWMeICIUFjY291bnRhYmxlXFN5c3RlbVxWMVxHUEJNZXRhZGF0YeoCF0FjY291bnRhYmxlOjpTeXN0ZW06OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message accountable.system.v1.GetRuntimeRequest
 */
export type GetRuntimeRequest = Message<"accountable.system.v1.GetRuntimeRequest"> & {
};

/**
 * Describes the message accountable.system.v1.GetRuntimeRequest.
 * Use `create(GetRuntimeRequestSchema)` to create a new message.
 */
export const GetRuntimeRequestSchema: GenMessage<GetRuntimeRequest> = /*@__PURE__*/
  messageDesc(file_accountable_system_v1_system, 0);

/**
 * @generated from message accountable.system.v1.GetRuntimeResponse
 */
export type GetRuntimeResponse = Message<"accountable.system.v1.GetRuntimeResponse"> & {
  /**
   * @generated from field: string release_id = 1;
   */
  releaseId: string;

  /**
   * @generated from field: google.protobuf.Timestamp server_time = 2;
   */
  serverTime?: Timestamp | undefined;

  /**
   * @generated from field: string request_id = 3;
   */
  requestId: string;
};

/**
 * Describes the message accountable.system.v1.GetRuntimeResponse.
 * Use `create(GetRuntimeResponseSchema)` to create a new message.
 */
export const GetRuntimeResponseSchema: GenMessage<GetRuntimeResponse> = /*@__PURE__*/
  messageDesc(file_accountable_system_v1_system, 1);

/**
 * @generated from service accountable.system.v1.SystemService
 */
export const SystemService: GenService<{
  /**
   * @generated from rpc accountable.system.v1.SystemService.GetRuntime
   */
  getRuntime: {
    methodKind: "unary";
    input: typeof GetRuntimeRequestSchema;
    output: typeof GetRuntimeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_accountable_system_v1_system, 0);

