// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file accountable/error/v1/problem.proto (package accountable.error.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file accountable/error/v1/problem.proto.
 */
export const file_accountable_error_v1_problem: GenFile = /*@__PURE__*/
  fileDesc("CiJhY2NvdW50YWJsZS9lcnJvci92MS9wcm9ibGVtLnByb3RvEhRhY2NvdW50YWJsZS5lcnJvci52MSLKAQoNUHJvYmxlbURldGFpbBIMCgRjb2RlGAEgASgJEhMKC21lc3NhZ2Vfa2V5GAIgASgJEhIKCnByb2JsZW1faWQYAyABKAkSEgoKcmVxdWVzdF9pZBgEIAEoCRI+ChBmaWVsZF92aW9sYXRpb25zGAUgAygLMiQuYWNjb3VudGFibGUuZXJyb3IudjEuRmllbGRWaW9sYXRpb24SLgoLcmV0cnlfYWZ0ZXIYBiABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24iMgoORmllbGRWaW9sYXRpb24SEgoKZmllbGRfcGF0aBgBIAEoCRIMCgRjb2RlGAIgASgJQt8BChhjb20uYWNjb3VudGFibGUuZXJyb3IudjFCDFByb2JsZW1Qcm90b1ABWkFnaXRodWIuY29tL2FjY3RibC9hY2NvdW50YWJsZS9nZW4vZ28vYWNjb3VudGFibGUvZXJyb3IvdjE7ZXJyb3J2MaICA0FFWKoCFEFjY291bnRhYmxlLkVycm9yLlYxygIVQWNjb3VudGFibGVcRXJyb3JfXFYx4gIhQWNjb3VudGFibGVcRXJyb3JfXFYxXEdQQk1ldGFkYXRh6gIWQWNjb3VudGFibGU6OkVycm9yOjpWMWIGcHJvdG8z", [file_google_protobuf_duration]);

/**
 * ProblemDetail is the only structured error detail exposed by the API.
 * message_key selects client-owned copy; it never contains user data or
 * server-authored English. Field violations carry stable machine codes.
 *
 * @generated from message accountable.error.v1.ProblemDetail
 */
export type ProblemDetail = Message<"accountable.error.v1.ProblemDetail"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string message_key = 2;
   */
  messageKey: string;

  /**
   * @generated from field: string problem_id = 3;
   */
  problemId: string;

  /**
   * @generated from field: string request_id = 4;
   */
  requestId: string;

  /**
   * @generated from field: repeated accountable.error.v1.FieldViolation field_violations = 5;
   */
  fieldViolations: FieldViolation[];

  /**
   * @generated from field: google.protobuf.Duration retry_after = 6;
   */
  retryAfter?: Duration | undefined;
};

/**
 * Describes the message accountable.error.v1.ProblemDetail.
 * Use `create(ProblemDetailSchema)` to create a new message.
 */
export const ProblemDetailSchema: GenMessage<ProblemDetail> = /*@__PURE__*/
  messageDesc(file_accountable_error_v1_problem, 0);

/**
 * @generated from message accountable.error.v1.FieldViolation
 */
export type FieldViolation = Message<"accountable.error.v1.FieldViolation"> & {
  /**
   * @generated from field: string field_path = 1;
   */
  fieldPath: string;

  /**
   * @generated from field: string code = 2;
   */
  code: string;
};

/**
 * Describes the message accountable.error.v1.FieldViolation.
 * Use `create(FieldViolationSchema)` to create a new message.
 */
export const FieldViolationSchema: GenMessage<FieldViolation> = /*@__PURE__*/
  messageDesc(file_accountable_error_v1_problem, 1);

