// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file accountable/common/v1/common.proto (package accountable.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file accountable/common/v1/common.proto.
 */
export const file_accountable_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("CiJhY2NvdW50YWJsZS9jb21tb24vdjEvY29tbW9uLnByb3RvEhVhY2NvdW50YWJsZS5jb21tb24udjEiRgoIU2NvcGVSZWYSLgoEa2luZBgBIAEoDjIgLmFjY291bnRhYmxlLmNvbW1vbi52MS5TY29wZUtpbmQSCgoCaWQYAiABKAkiawoLUmVzb3VyY2VSZWYSDgoGbW9kdWxlGAEgASgJEhUKDXJlc291cmNlX3R5cGUYAiABKAkSEwoLcmVzb3VyY2VfaWQYAyABKAkSFAoHdmVyc2lvbhgEIAEoBEgAiAEBQgoKCF92ZXJzaW9uIlUKDkNvbW1hbmRDb250cm9sEhcKD2lkZW1wb3RlbmN5X2tleRgBIAEoCRIZCgx2ZXJzaW9uX2V0YWcYAiABKAlIAIgBAUIPCg1fdmVyc2lvbl9ldGFnKqgBCglTY29wZUtpbmQSGgoWU0NPUEVfS0lORF9VTlNQRUNJRklFRBAAEhcKE1NDT1BFX0tJTkRfUExBVEZPUk0QARIYChRTQ09QRV9LSU5EX1dPUktTUEFDRRACEhUKEVNDT1BFX0tJTkRfRU5USVRZEAMSHgoaU0NPUEVfS0lORF9CSUxMSU5HX0FDQ09VTlQQBBIVChFTQ09QRV9LSU5EX1BFUlNPThAFQuMBChljb20uYWNjb3VudGFibGUuY29tbW9uLnYxQgtDb21tb25Qcm90b1ABWkNnaXRodWIuY29tL2FjY3RibC9hY2NvdW50YWJsZS9nZW4vZ28vYWNjb3VudGFibGUvY29tbW9uL3YxO2NvbW1vbnYxogIDQUNYqgIVQWNjb3VudGFibGUuQ29tbW9uLlYxygIVQWNjb3VudGFibGVcQ29tbW9uXFYx4gIhQWNjb3VudGFibGVcQ29tbW9uXFYxXEdQQk1ldGFkYXRh6gIXQWNjb3VudGFibGU6OkNvbW1vbjo6VjFiBnByb3RvMw");

/**
 * @generated from message accountable.common.v1.ScopeRef
 */
export type ScopeRef = Message<"accountable.common.v1.ScopeRef"> & {
  /**
   * @generated from field: accountable.common.v1.ScopeKind kind = 1;
   */
  kind: ScopeKind;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message accountable.common.v1.ScopeRef.
 * Use `create(ScopeRefSchema)` to create a new message.
 */
export const ScopeRefSchema: GenMessage<ScopeRef> = /*@__PURE__*/
  messageDesc(file_accountable_common_v1_common, 0);

/**
 * @generated from message accountable.common.v1.ResourceRef
 */
export type ResourceRef = Message<"accountable.common.v1.ResourceRef"> & {
  /**
   * @generated from field: string module = 1;
   */
  module: string;

  /**
   * @generated from field: string resource_type = 2;
   */
  resourceType: string;

  /**
   * @generated from field: string resource_id = 3;
   */
  resourceId: string;

  /**
   * @generated from field: optional uint64 version = 4;
   */
  version?: bigint | undefined;
};

/**
 * Describes the message accountable.common.v1.ResourceRef.
 * Use `create(ResourceRefSchema)` to create a new message.
 */
export const ResourceRefSchema: GenMessage<ResourceRef> = /*@__PURE__*/
  messageDesc(file_accountable_common_v1_common, 1);

/**
 * @generated from message accountable.common.v1.CommandControl
 */
export type CommandControl = Message<"accountable.common.v1.CommandControl"> & {
  /**
   * @generated from field: string idempotency_key = 1;
   */
  idempotencyKey: string;

  /**
   * @generated from field: optional string version_etag = 2;
   */
  versionEtag?: string | undefined;
};

/**
 * Describes the message accountable.common.v1.CommandControl.
 * Use `create(CommandControlSchema)` to create a new message.
 */
export const CommandControlSchema: GenMessage<CommandControl> = /*@__PURE__*/
  messageDesc(file_accountable_common_v1_common, 2);

/**
 * @generated from enum accountable.common.v1.ScopeKind
 */
export enum ScopeKind {
  /**
   * @generated from enum value: SCOPE_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCOPE_KIND_PLATFORM = 1;
   */
  PLATFORM = 1,

  /**
   * @generated from enum value: SCOPE_KIND_WORKSPACE = 2;
   */
  WORKSPACE = 2,

  /**
   * @generated from enum value: SCOPE_KIND_ENTITY = 3;
   */
  ENTITY = 3,

  /**
   * @generated from enum value: SCOPE_KIND_BILLING_ACCOUNT = 4;
   */
  BILLING_ACCOUNT = 4,

  /**
   * @generated from enum value: SCOPE_KIND_PERSON = 5;
   */
  PERSON = 5,
}

/**
 * Describes the enum accountable.common.v1.ScopeKind.
 */
export const ScopeKindSchema: GenEnum<ScopeKind> = /*@__PURE__*/
  enumDesc(file_accountable_common_v1_common, 0);

