// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file accountable/common/v1/common.proto (package accountable.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file accountable/common/v1/common.proto.
 */
export const file_accountable_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("CiJhY2NvdW50YWJsZS9jb21tb24vdjEvY29tbW9uLnByb3RvEhVhY2NvdW50YWJsZS5jb21tb24udjEiTAoIU2NvcGVSZWYSLgoEa2luZBgBIAEoDjIgLmFjY291bnRhYmxlLmNvbW1vbi52MS5TY29wZUtpbmQSEAoIc2NvcGVfaWQYAiABKAkiaQoLUmVzb3VyY2VSZWYSLgoFc2NvcGUYASABKAsyHy5hY2NvdW50YWJsZS5jb21tb24udjEuU2NvcGVSZWYSFQoNcmVzb3VyY2VfdHlwZRgCIAEoCRITCgtyZXNvdXJjZV9pZBgDIAEoCSJVCg5Db21tYW5kQ29udHJvbBIXCg9pZGVtcG90ZW5jeV9rZXkYASABKAkSGQoMdmVyc2lvbl9ldGFnGAIgASgJSACIAQFCDwoNX3ZlcnNpb25fZXRhZypzCglTY29wZUtpbmQSGgoWU0NPUEVfS0lORF9VTlNQRUNJRklFRBAAEhsKF1NDT1BFX0tJTkRfT1JHQU5JWkFUSU9OEAESGAoUU0NPUEVfS0lORF9XT1JLU1BBQ0UQAhITCg9TQ09QRV9LSU5EX1VTRVIQA0LjAQoZY29tLmFjY291bnRhYmxlLmNvbW1vbi52MUILQ29tbW9uUHJvdG9QAVpDZ2l0aHViLmNvbS9hY2N0YmwvYWNjb3VudGFibGUvZ2VuL2dvL2FjY291bnRhYmxlL2NvbW1vbi92MTtjb21tb252MaICA0FDWKoCFUFjY291bnRhYmxlLkNvbW1vbi5WMcoCFUFjY291bnRhYmxlXENvbW1vblxWMeICIUFjY291bnRhYmxlXENvbW1vblxWMVxHUEJNZXRhZGF0YeoCF0FjY291bnRhYmxlOjpDb21tb246OlYxYgZwcm90bzM");

/**
 * ScopeRef is the stable, typed reference to an owning scope.
 *
 * @generated from message accountable.common.v1.ScopeRef
 */
export type ScopeRef = Message<"accountable.common.v1.ScopeRef"> & {
  /**
   * @generated from field: accountable.common.v1.ScopeKind kind = 1;
   */
  kind: ScopeKind;

  /**
   * @generated from field: string scope_id = 2;
   */
  scopeId: string;
};

/**
 * Describes the message accountable.common.v1.ScopeRef.
 * Use `create(ScopeRefSchema)` to create a new message.
 */
export const ScopeRefSchema: GenMessage<ScopeRef> = /*@__PURE__*/
  messageDesc(file_accountable_common_v1_common, 0);

/**
 * ResourceRef identifies a resource without embedding a generated DTO in a
 * domain package.
 *
 * @generated from message accountable.common.v1.ResourceRef
 */
export type ResourceRef = Message<"accountable.common.v1.ResourceRef"> & {
  /**
   * @generated from field: accountable.common.v1.ScopeRef scope = 1;
   */
  scope?: ScopeRef | undefined;

  /**
   * @generated from field: string resource_type = 2;
   */
  resourceType: string;

  /**
   * @generated from field: string resource_id = 3;
   */
  resourceId: string;
};

/**
 * Describes the message accountable.common.v1.ResourceRef.
 * Use `create(ResourceRefSchema)` to create a new message.
 */
export const ResourceRefSchema: GenMessage<ResourceRef> = /*@__PURE__*/
  messageDesc(file_accountable_common_v1_common, 1);

/**
 * CommandControl carries transport-safe command execution controls.
 *
 * @generated from message accountable.common.v1.CommandControl
 */
export type CommandControl = Message<"accountable.common.v1.CommandControl"> & {
  /**
   * @generated from field: string idempotency_key = 1;
   */
  idempotencyKey: string;

  /**
   * @generated from field: optional string version_etag = 2;
   */
  versionEtag?: string | undefined;
};

/**
 * Describes the message accountable.common.v1.CommandControl.
 * Use `create(CommandControlSchema)` to create a new message.
 */
export const CommandControlSchema: GenMessage<CommandControl> = /*@__PURE__*/
  messageDesc(file_accountable_common_v1_common, 2);

/**
 * ScopeKind identifies the class of boundary in which a resource lives.
 *
 * @generated from enum accountable.common.v1.ScopeKind
 */
export enum ScopeKind {
  /**
   * @generated from enum value: SCOPE_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCOPE_KIND_ORGANIZATION = 1;
   */
  ORGANIZATION = 1,

  /**
   * @generated from enum value: SCOPE_KIND_WORKSPACE = 2;
   */
  WORKSPACE = 2,

  /**
   * @generated from enum value: SCOPE_KIND_USER = 3;
   */
  USER = 3,
}

/**
 * Describes the enum accountable.common.v1.ScopeKind.
 */
export const ScopeKindSchema: GenEnum<ScopeKind> = /*@__PURE__*/
  enumDesc(file_accountable_common_v1_common, 0);

