// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file accountable/type/v1/localized_error.proto (package accountable.type.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file accountable/type/v1/localized_error.proto.
 */
export const file_accountable_type_v1_localized_error: GenFile = /*@__PURE__*/
  fileDesc("CilhY2NvdW50YWJsZS90eXBlL3YxL2xvY2FsaXplZF9lcnJvci5wcm90bxITYWNjb3VudGFibGUudHlwZS52MSIlCg5Mb2NhbGl6ZWRFcnJvchITCgttZXNzYWdlX2tleRgBIAEoCULdAQoXY29tLmFjY291bnRhYmxlLnR5cGUudjFCE0xvY2FsaXplZEVycm9yUHJvdG9QAVo/Z2l0aHViLmNvbS9hY2N0YmwvYWNjb3VudGFibGUvZ2VuL2dvL2FjY291bnRhYmxlL3R5cGUvdjE7dHlwZXYxogIDQVRYqgITQWNjb3VudGFibGUuVHlwZS5WMcoCE0FjY291bnRhYmxlXFR5cGVcVjHiAh9BY2NvdW50YWJsZVxUeXBlXFYxXEdQQk1ldGFkYXRh6gIVQWNjb3VudGFibGU6OlR5cGU6OlYxYgZwcm90bzM");

/**
 * @generated from message accountable.type.v1.LocalizedError
 */
export type LocalizedError = Message<"accountable.type.v1.LocalizedError"> & {
  /**
   * @generated from field: string message_key = 1;
   */
  messageKey: string;
};

/**
 * Describes the message accountable.type.v1.LocalizedError.
 * Use `create(LocalizedErrorSchema)` to create a new message.
 */
export const LocalizedErrorSchema: GenMessage<LocalizedError> = /*@__PURE__*/
  messageDesc(file_accountable_type_v1_localized_error, 0);

